name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Enable caching and define a custom cache key suffix
      id: setup-uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-suffix: "optional-suffix"
    - name: Install Dependencies
      run: uv pip install -r pyproject.toml --extra dev
    - uses: pre-commit/action@v3.0.1
